name: Mycheck
on: pull_request

jobs:
  Mycheck:
    name: Mycheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: script/mycheck.sh "$GITHUB_SHA" "$GITHUB_REF"